const countryCodes = [
    { code: "+1", name: "USA" },
    { code: "+1", name: "Canada" },
    { code: "+52", name: "Mexico" },
    { code: "+852", name: "Hong Kong" },
    { code: "+44", name: "UK" },
    { code: "+33", name: "France" },
    { code: "+49", name: "Germany" },
    { code: "+66", name: "Thailand" },
    { code: "+84", name: "Vietnam" },
    { code: "+91", name: "India" },
    { code: "+27", name: "South Africa" },
    { code: "+61", name: "Australia" },
    { code: "+64", name: "New Zealand" },
    { code: "+971", name: "UAE" },
    { code: "+81", name: "Japan" },
    { code: "+82", name: "South Korea" },
    { code: "+39", name: "Italy" },
    { code: "+30", name: "Greece" },
    { code: "+90", name: "Turkey" },
    { code: "+55", name: "Brazil" },
    { code: "+54", name: "Argentina" },
    { code: "+56", name: "Chile" },
    // Add more countries as needed
    ];
export default countryCodes